package com.saga.activities;

import com.saga.common.model.PaymentEvent;
import com.saga.common.model.InventoryEvent;
import com.saga.common.model.ShippingEvent;
import com.saga.common.constants.PaymentEventType;
import com.saga.common.constants.InventoryEventType;
import com.saga.common.constants.ShippingEventType;
import com.saga.config.RabbitConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import java.math.BigDecimal;

/**
 * Implementation of OrderActivities.
 * Handles all RabbitMQ event publishing for the saga workflow.
 *
 * Key benefits of using Activities:
 * 1. Workflow code remains deterministic (can be replayed safely)
 * 2. Activities can be retried independently with different policies
 * 3. Side effects are isolated from workflow logic
 * 4. Better observability and debugging
 */
@Component
public class OrderActivitiesImpl implements OrderActivities {
    
    private static final Logger logger = LoggerFactory.getLogger(OrderActivitiesImpl.class);

    @Autowired
    private RabbitTemplate rabbitTemplate;

    @Override
    public void publishPaymentRequest(String orderId) {
        logger.info("Activity: Publishing PROCESS_PAYMENT event for order: {}", orderId);
        try {
            // Create payment event with sample data (in real scenario, these would come from order details)
            PaymentEvent event = new PaymentEvent(
                orderId, 
                PaymentEventType.PROCESS_PAYMENT,
                new BigDecimal("100.00"), // Sample amount
                "USD",
                "CREDIT_CARD"
            );
            rabbitTemplate.convertAndSend(RabbitConfig.SAGA_EXCHANGE, RabbitConfig.PAYMENT_ROUTING_KEY, event);
            logger.info("Activity: Successfully published PROCESS_PAYMENT event for order: {}", orderId);
        } catch (Exception e) {
            logger.error("Activity: Failed to publish PROCESS_PAYMENT event for order: {}", orderId, e);
            throw new RuntimeException("Failed to publish payment request", e);
        }
    }
    
    @Override
    public void publishInventoryRequest(String orderId) {
        logger.info("Activity: Publishing RESERVE_INVENTORY event for order: {}", orderId);
        try {
            // Create inventory event with sample data (in real scenario, these would come from order details)
            InventoryEvent event = new InventoryEvent(
                orderId, 
                InventoryEventType.RESERVE_INVENTORY,
                "PROD-123", // Sample product ID
                2, // Sample quantity
                "WAREHOUSE-001"
            );
            rabbitTemplate.convertAndSend(RabbitConfig.SAGA_EXCHANGE, RabbitConfig.INVENTORY_ROUTING_KEY, event);
            logger.info("Activity: Successfully published RESERVE_INVENTORY event for order: {}", orderId);
        } catch (Exception e) {
            logger.error("Activity: Failed to publish RESERVE_INVENTORY event for order: {}", orderId, e);
            throw new RuntimeException("Failed to publish inventory request", e);
        }
    }
    
    @Override
    public void publishShippingRequest(String orderId) {
        logger.info("Activity: Publishing PROCESS_SHIPPING event for order: {}", orderId);
        try {
            // Create shipping event with sample data (in real scenario, these would come from order details)
            ShippingEvent event = new ShippingEvent(
                orderId, 
                ShippingEventType.PROCESS_SHIPPING,
                "123 Main St, City, Country", // Sample address
                null, // Tracking number will be generated by shipping service
                null // Carrier will be assigned by shipping service
            );
            rabbitTemplate.convertAndSend(RabbitConfig.SAGA_EXCHANGE, RabbitConfig.SHIPPING_ROUTING_KEY, event);
            logger.info("Activity: Successfully published PROCESS_SHIPPING event for order: {}", orderId);
        } catch (Exception e) {
            logger.error("Activity: Failed to publish PROCESS_SHIPPING event for order: {}", orderId, e);
            throw new RuntimeException("Failed to publish shipping request", e);
        }
    }
    
    @Override
    public void compensatePayment(String orderId) {
        logger.warn("Activity: Compensating payment for order: {}", orderId);
        try {
            PaymentEvent event = new PaymentEvent(orderId, PaymentEventType.COMPENSATE_PAYMENT);
            rabbitTemplate.convertAndSend(RabbitConfig.SAGA_EXCHANGE, RabbitConfig.PAYMENT_ROUTING_KEY, event);
            logger.info("Activity: Successfully published COMPENSATE_PAYMENT event for order: {}", orderId);
        } catch (Exception e) {
            logger.error("Activity: Failed to compensate payment for order: {}", orderId, e);
            throw new RuntimeException("Failed to compensate payment", e);
        }
    }
    
    @Override
    public void compensateInventory(String orderId) {
        logger.warn("Activity: Compensating inventory reservation for order: {}", orderId);
        try {
            InventoryEvent event = new InventoryEvent(orderId, InventoryEventType.COMPENSATE_INVENTORY);
            rabbitTemplate.convertAndSend(RabbitConfig.SAGA_EXCHANGE, RabbitConfig.INVENTORY_ROUTING_KEY, event);
            logger.info("Activity: Successfully published COMPENSATE_INVENTORY event for order: {}", orderId);
        } catch (Exception e) {
            logger.error("Activity: Failed to compensate inventory for order: {}", orderId, e);
            throw new RuntimeException("Failed to compensate inventory", e);
        }
    }
    
    @Override
    public void compensateShipping(String orderId) {
        logger.warn("Activity: Compensating shipping for order: {}", orderId);
        try {
            ShippingEvent event = new ShippingEvent(orderId, ShippingEventType.COMPENSATE_SHIPPING);
            rabbitTemplate.convertAndSend(RabbitConfig.SAGA_EXCHANGE, RabbitConfig.SHIPPING_ROUTING_KEY, event);
            logger.info("Activity: Successfully published COMPENSATE_SHIPPING event for order: {}", orderId);
        } catch (Exception e) {
            logger.error("Activity: Failed to compensate shipping for order: {}", orderId, e);
            throw new RuntimeException("Failed to compensate shipping", e);
        }
    }
}
